#!/usr/bin/env python3
from pathlib import Path
import os
import shutil
import subprocess

LAYOUT_IMAGES = [
    "final_routing.webp",
    "final_placement.webp",
    "final_worst_path.webp",
]

REPO_URL = "https://github.com/abarajithan11/digital-design"


def run_in_container(ci_image: str, cmd: str) -> str:
    command = ["make", "run", f"CI_IMAGE={ci_image}", f"CMD={cmd}"]
    result = subprocess.run(command, check=False)
    return "pass" if result.returncode == 0 else "fail"


def main() -> None:
    repo = Path(__file__).resolve().parents[1]
    os.chdir(repo)

    ci_image = os.environ.get("CI_IMAGE", "pages-layouts:latest")
    sim_status_file = repo / "out" / "sim" / "status.tsv"
    docs_md = repo / "docs" / "design_outputs.md"
    assets_root = repo / "docs" / "assets" / "design-outputs"

    if assets_root.exists():
        shutil.rmtree(assets_root)
    assets_root.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Design Outputs",
        "",
        "Generated by GitHub Actions from simulation and OpenROAD reports.",
        "",
    ]

    if not sim_status_file.exists() or sim_status_file.stat().st_size == 0:
        lines.append("No designs found under material/designs.")
        docs_md.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return

    for row in sim_status_file.read_text(encoding="utf-8").splitlines():
        if not row.strip():
            continue

        design, sim_status = row.split("\t", maxsplit=1)
        sim_svg_status = run_in_container(ci_image, f"make wave_svg DESIGN={design}")
        gds_status = run_in_container(ci_image, f"make gds DESIGN={design}")

        sim_result = "passed" if sim_status.strip().lower() == "pass" else "failed"
        rtl2gds_result = "passed" if gds_status.strip().lower() == "pass" else "failed"

        sim_link = f"{REPO_URL}/blob/main/material/tb/tb_{design}.sv"
        rtl2gds_link = f"{REPO_URL}/tree/main/material/openroad"

        dst = assets_root / design
        dst.mkdir(parents=True, exist_ok=True)

        sim_svg = repo / "material" / "sim" / design / f"{design}.svg"
        if sim_svg.exists():
            shutil.copy2(sim_svg, dst / f"{design}.svg")

        src_layout = repo / "material" / "openroad" / "work" / "reports" / "asap7" / design / "base"
        for image in LAYOUT_IMAGES:
            source_image = src_layout / image
            if source_image.exists():
                shutil.copy2(source_image, dst / image)

        lines.extend(
            [
                f"## {design}",
                "",
                f"- [Simulation]({sim_link}): {sim_result}",
                f"- [RTL2GDS]({rtl2gds_link}): {rtl2gds_result}",
                f"- waveform_svg: {'passed' if sim_svg_status.strip().lower() == 'pass' else 'failed'}",
                "",
                "### Simulation Waveform",
                "",
            ]
        )

        if (dst / f"{design}.svg").exists():
            lines.append(f"![{design} waveform](assets/design-outputs/{design}/{design}.svg)")
        else:
            lines.append("Waveform SVG not generated.")
        lines.append("")

        lines.extend([
            "### Layout Reports",
            "",
        ])

        routing_path = f"assets/design-outputs/{design}/final_routing.webp"
        placement_path = f"assets/design-outputs/{design}/final_placement.webp"
        worst_path = f"assets/design-outputs/{design}/final_worst_path.webp"

        if all((dst / image).exists() for image in LAYOUT_IMAGES):
            lines.extend([
                '<div style="display:flex; gap:12px; justify-content:center; align-items:flex-start;">',
                f'  <img src="{routing_path}" alt="{design} routing" style="width:32%; height:auto;" />',
                f'  <img src="{placement_path}" alt="{design} placement" style="width:32%; height:auto;" />',
                f'  <img src="{worst_path}" alt="{design} worst path" style="width:32%; height:auto;" />',
                "</div>",
                '<p style="text-align:center;"><em>Routing, Placement, Worst path</em></p>',
                "",
            ])
        else:
            lines.append("One or more layout images were not generated.")
            lines.append("")

    docs_md.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()