#!/usr/bin/env python3
from pathlib import Path
import os
import shutil
import subprocess

IMAGES = [
    "final_all.webp",
    "final_placement.webp",
    "final_routing.webp",
    "final_worst_path.webp",
]


def run_gds(design: str, ci_image: str) -> str:
    cmd = ["make", "run", f"CI_IMAGE={ci_image}", f"CMD=make gds DESIGN={design}"]
    result = subprocess.run(cmd, check=False)
    return "pass" if result.returncode == 0 else "fail"


def main() -> None:
    repo = Path(__file__).resolve().parents[1]
    os.chdir(repo)

    ci_image = os.environ.get("CI_IMAGE", "pages-layouts:latest")
    sim_status_file = repo / "out" / "sim" / "status.tsv"
    docs_md = repo / "docs" / "asap7-layouts.md"
    assets_root = repo / "docs" / "assets" / "asap7-layouts"

    assets_root.mkdir(parents=True, exist_ok=True)

    lines = [
        "# ASAP7 layouts",
        "",
        "Generated by GitHub Actions from OpenROAD ASAP7 reports.",
        "",
    ]

    if not sim_status_file.exists() or sim_status_file.stat().st_size == 0:
        lines.append("No designs found under material/designs.")
        docs_md.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return

    for row in sim_status_file.read_text(encoding="utf-8").splitlines():
        if not row.strip():
            continue
        design, sim_status = row.split("\t", maxsplit=1)
        gds_status = run_gds(design, ci_image)

        src = repo / "material" / "openroad" / "work" / "reports" / "asap7" / design / "base"
        dst = assets_root / design
        dst.mkdir(parents=True, exist_ok=True)

        for image in IMAGES:
            source_image = src / image
            if source_image.exists():
                shutil.copy2(source_image, dst / image)

        lines.extend([
            f"## {design}",
            "",
            f"- sim: **{sim_status}**",
            f"- gds: **{gds_status}**",
            "",
        ])

        for image in IMAGES:
            lines.append(f"### {image.removesuffix('.webp')}")
            lines.append("")
            if (dst / image).exists():
                lines.append(f"![{design} {image.removesuffix('.webp')}](assets/asap7-layouts/{design}/{image})")
            else:
                lines.append("Image not generated.")
            lines.append("")

    docs_md.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
